use leptos::*;
use leptos_meta::*;
use leptos_router::*;

use crate::components::nav::NavBar;
use crate::pages::home::HomePage;
use crate::pages::tech_graph_page::TechGraphPage;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();
    
    view! {
        <Title text="Sci-Fi Tech-Verse"/>
        <Meta name="description" content="A visualization of technologies in science fiction."/>
        <Stylesheet id="leptos" href="/pkg/frontend.css"/> // Points to CSS generated by cargo-leptos

        <Router>
            <NavBar />
            <main class="container">
                <Routes>
                    <Route path="" view=HomePage />
                    <Route path="/tech-graph" view=TechGraphPage />
                </Routes>
            </main>
        </Router>
    }
} 